import { NextRequest, NextResponse } from 'next/server';
import { databaseConfigured, db } from '../../../lib/db';
import { authConfigured, sessionValid } from '../../../lib/auth';
import { ensureCrmSchema } from '../../../lib/ensure-schema';
export const runtime='nodejs'; export const dynamic='force-dynamic'; const headers={'Cache-Control':'no-store'};
const statuses=new Set(['À contacter','RDV','Réalisé','Perdu']);
const fields=`id,name,phone,email,vehicle,registration,source,status,service_type as "serviceType",estimated_amount::float8 as "estimatedAmount",paid_amount::float8 as "paidAmount",generated_revenue::float8 as "generatedRevenue",appointment_at as "appointmentAt",satisfaction_stars as "satisfactionStars",next_action as "nextAction",next_action_at as "nextActionAt",last_contact_at as "lastContactAt",consent_status as "consentStatus",notes,created_at as "createdAt",updated_at as "updatedAt"`;
async function guard(){if(!databaseConfigured())return NextResponse.json({error:'database_not_configured'},{status:503,headers});if(!authConfigured())return NextResponse.json({error:'secure_access_not_configured'},{status:503,headers});if(!(await sessionValid()))return NextResponse.json({error:'unauthorized'},{status:401,headers});await ensureCrmSchema();return null}
export async function GET(){const denied=await guard();if(denied)return denied;try{const items=await db().unsafe(`select ${fields} from individual_customers where deleted_at is null order by updated_at desc`);return NextResponse.json({mode:'postgresql',items},{headers})}catch{return NextResponse.json({error:'database_unavailable'},{status:503,headers})}}
export async function POST(req:NextRequest){const denied=await guard();if(denied)return denied;let x:any;try{x=await req.json()}catch{return NextResponse.json({error:'invalid_request'},{status:400,headers})}const name=String(x.name||'').trim(),registration=String(x.registration||'').trim().toUpperCase(),status=String(x.status||'À contacter'),revenue=Number(x.generatedRevenue??0),estimated=Number(x.estimatedAmount??0),paid=Number(x.paidAmount??0),stars=x.satisfactionStars==null||x.satisfactionStars===''?null:Number(x.satisfactionStars);if(!name||!registration||!statuses.has(status)||![revenue,estimated,paid].every(n=>Number.isFinite(n)&&n>=0)||(stars!==null&&(!Number.isInteger(stars)||stars<1||stars>5)))return NextResponse.json({error:'invalid_customer'},{status:400,headers});try{const duplicate=await db()`select id from individual_customers where deleted_at is null and upper(registration)=upper(${registration}) limit 1`;if(duplicate.length)return NextResponse.json({error:'registration_exists'},{status:409,headers});const result=await db().begin(async sql=>{const rows=await sql`insert into individual_customers(name,phone,email,vehicle,registration,source,status,service_type,estimated_amount,paid_amount,generated_revenue,appointment_at,satisfaction_stars,next_action,next_action_at,last_contact_at,consent_status,notes) values(${name},${String(x.phone||'')},${String(x.email||'')},${String(x.vehicle||'')},${registration},${String(x.source||'Apport personnel')},${status},${String(x.serviceType||'Remplacement de vitrage')},${estimated},${paid},${revenue},${x.appointmentAt||null},${stars},${String(x.nextAction||'')},${x.nextActionAt||null},${x.lastContactAt||null},${String(x.consentStatus||'À vérifier')},${String(x.notes||'')}) returning id`;if(rows.length)await sql`insert into individual_customer_events(customer_id,event_type,payload) values(${rows[0].id},'created',${sql.json({source:'crm'})})`;const saved=await sql`select id,name,phone,email,vehicle,registration,source,status,service_type as "serviceType",estimated_amount::float8 as "estimatedAmount",paid_amount::float8 as "paidAmount",generated_revenue::float8 as "generatedRevenue",appointment_at as "appointmentAt",satisfaction_stars as "satisfactionStars",next_action as "nextAction",next_action_at as "nextActionAt",last_contact_at as "lastContactAt",consent_status as "consentStatus",notes,created_at as "createdAt",updated_at as "updatedAt" from individual_customers where id=${rows[0].id}`;return saved[0]});return NextResponse.json({item:result},{status:201,headers})}catch{return NextResponse.json({error:'database_unavailable'},{status:503,headers})}}
