'use client';
import { useEffect, useMemo, useState } from 'react';
type Routine={id:string;title:string;details:string|null;period:'daily'|'weekly'|'monthly'|'yearly';priority:number;dueAt:string|null;recurring:boolean};
type Recommendation={prospectId:string;prospect:string;priority:number;weightedPotential:number;action:string};
type Props={recommendations:Recommendation[]};
const periods=[['daily','Aujourd’hui'],['weekly','Cette semaine'],['monthly','Ce mois'],['yearly','Cette année']] as const;
const periodLabel=(key:string)=>periods.find(([id])=>id===key)?.[1]||key;
const nextDefault=(period:string)=>{const d=new Date();if(period==='daily')d.setHours(17,0,0,0);else if(period==='weekly'){d.setDate(d.getDate()+((8-d.getDay())%7||7));d.setHours(17,0,0,0)}else if(period==='monthly'){d.setMonth(d.getMonth()+1,0);d.setHours(17,0,0,0)}else{d.setMonth(11,31);d.setHours(17,0,0,0)}return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export default function CommercialTaskPlanner({recommendations}:Props){
 const[tasks,setTasks]=useState<Routine[]>([]),[period,setPeriod]=useState<string>('daily'),[title,setTitle]=useState(''),[details,setDetails]=useState(''),[dueAt,setDueAt]=useState(nextDefault('daily')),[priority,setPriority]=useState(65),[recurring,setRecurring]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){try{const r=await fetch('/api/routines',{cache:'no-store'});if(r.status===401){location.href='/login';return}if(!r.ok)throw new Error();const d=await r.json();setTasks(d.tasks||[]);setError('')}catch{setError('Le stockage des routines est indisponible pour le moment.')}}
 useEffect(()=>{load()},[]);
 const viewTasks=useMemo(()=>tasks.filter(t=>t.period===period),[tasks,period]);
 const urgent=useMemo(()=>recommendations.filter(r=>r.priority>=75),[recommendations]);
 const potentialCut=useMemo(()=>{const vals=recommendations.map(r=>r.weightedPotential).sort((a,b)=>a-b);return vals.length?vals[Math.floor(vals.length/2)]:0},[recommendations]);
 async function add(e:React.FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);try{const r=await fetch('/api/routines',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,details,period,priority,dueAt:new Date(dueAt).toISOString(),recurring})});if(!r.ok)throw new Error();setTitle('');setDetails('');setRecurring(false);await load()}catch{setError('La tâche n’a pas pu être enregistrée.')}finally{setBusy(false)}}
 async function close(id:string){setBusy(true);try{const r=await fetch('/api/routines',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'close',id})});if(!r.ok)throw new Error();await load()}catch{setError('La tâche n’a pas pu être clôturée.')}finally{setBusy(false)}}
 const css=`.planner{display:grid;gap:15px}.plannerHead{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}.plannerHead h2{margin:3px 0}.plannerMatrix{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.plannerQuad{padding:13px;border:1px solid #e7eaf0;border-radius:12px;background:#fafbfc}.plannerQuad b{display:block;font-size:12px}.plannerQuad span{font-size:10px;color:#657186}.plannerTabs{display:flex;gap:7px;flex-wrap:wrap}.plannerTabs button{padding:8px 11px;border:1px solid #e1e6ed;border-radius:9px;background:#fff;color:#445166;font-size:10px}.plannerTabs button.active{background:#111c2a;color:#fff;border-color:#111c2a}.plannerForm{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px;border-radius:12px;background:#f6f8fa}.plannerForm label{font-size:10px;color:#596679}.plannerForm input,.plannerForm select,.plannerForm textarea{display:block;width:100%;padding:9px;margin-top:5px;border:1px solid #dce1e9;border-radius:8px;background:#fff}.plannerForm .wide{grid-column:1/-1}.plannerForm button{justify-self:start}.plannerTask{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:12px 0;border-top:1px solid #edf0f4}.plannerTask:first-of-type{border-top:0}.plannerTask small{display:block;color:#778397;margin-top:4px}.plannerTask button{font-size:10px}.plannerRecurring{display:flex;align-items:center;gap:8px!important}.plannerError{color:#a4453f;font-size:11px}@media(max-width:700px){.plannerForm{grid-template-columns:1fr}.plannerForm .wide{grid-column:auto}.plannerMatrix{grid-template-columns:1fr}.plannerHead{flex-direction:column}}`;
 return <section className="actionPanel planner"><style>{css}</style><div className="plannerHead"><div><p className="eyebrow">PILOTAGE COMMERCIAL</p><h2>Priorités & routines</h2><p className="muted">Classe les opportunités par urgence et potentiel, puis organise tes actions sur quatre horizons.</p></div><span className="confidence">{tasks.length} routine(s) ouverte(s)</span></div>
 <div className="plannerMatrix"><div className="plannerQuad"><b>À faire d’abord · urgent + potentiel</b><span>{urgent.filter(r=>r.weightedPotential>=potentialCut).length} opportunités à fort enjeu</span></div><div className="plannerQuad"><b>À planifier · potentiel à construire</b><span>{recommendations.filter(r=>r.priority<75&&r.weightedPotential>=potentialCut).length} opportunités à programmer</span></div><div className="plannerQuad"><b>À traiter vite · faible potentiel</b><span>{recommendations.filter(r=>r.priority>=75&&r.weightedPotential<potentialCut).length} sujets urgents à qualifier</span></div><div className="plannerQuad"><b>À suivre sans urgence</b><span>{recommendations.filter(r=>r.priority<75&&r.weightedPotential<potentialCut).length} opportunités en veille active</span></div></div>
 <div className="plannerTabs">{periods.map(([key,label])=><button type="button" className={period===key?'active':''} key={key} onClick={()=>{setPeriod(key);setDueAt(nextDefault(key))}}>{label} · {tasks.filter(t=>t.period===key).length}</button>)}</div>
 <form className="plannerForm" onSubmit={add}><label className="wide">Tâche à ajouter<input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Préparer les relances du secteur"/></label><label className="wide">Notes / résultat attendu<textarea rows={2} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Contexte ou résultat attendu"/></label><label>Échéance<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>Priorité<select value={priority} onChange={e=>setPriority(Number(e.target.value))}><option value={90}>Critique · 90</option><option value={75}>Haute · 75</option><option value={60}>Normale · 60</option><option value={35}>Basse · 35</option></select></label><label className="plannerRecurring wide"><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Répéter automatiquement {periodLabel(period).toLowerCase()} après chaque validation</label><button className="primary" disabled={busy||!title.trim()}>Ajouter à ma routine</button></form>
 {error&&<p className="plannerError">{error}</p>}{viewTasks.length?viewTasks.map(t=><article className="plannerTask" key={t.id}><div><b>{t.title}</b>{t.details&&<small>{t.details}</small>}<small>{t.dueAt?new Date(t.dueAt).toLocaleString('fr-FR'):'Sans échéance'} · Priorité {t.priority}/100{t.recurring?' · récurrente':''}</small></div><button className="primary" disabled={busy} onClick={()=>close(t.id)}>Fait</button></article>):<p className="actionEmpty">Aucune tâche enregistrée pour cet horizon. Ajoute une routine ou une tâche ponctuelle ci-dessus.</p>}
 </section>;
}
