'use client';
import { useEffect, useMemo, useState } from 'react';
type Customer={id:string;name:string;phone:string;email:string|null;vehicle:string;registration:string;source:string;status:string;serviceType:string;estimatedAmount:number;paidAmount:number;generatedRevenue:number;appointmentAt:string|null;satisfactionStars:number|null;nextAction:string;nextActionAt:string|null;lastContactAt:string|null;consentStatus:string;notes:string};
const money=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v||0);
const toLocal=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
export default function IndividualManager(){
 const[items,setItems]=useState<Customer[]>([]),[query,setQuery]=useState(''),[editing,setEditing]=useState<Customer|null>(null),[open,setOpen]=useState(false),[blocked,setBlocked]=useState(true);
 async function load(){try{const r=await fetch('/api/individuals',{cache:'no-store'});if(r.status===401){location.href='/login';return}if(!r.ok){setBlocked(true);return}const d=await r.json();setItems(d.items||[]);setBlocked(false)}catch{setBlocked(true)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>(x.name+x.phone+x.email+x.vehicle+x.registration+x.nextAction).toLowerCase().includes(query.toLowerCase())),[items,query]);
 const fresh=():Customer=>({id:'',name:'',phone:'',email:'',vehicle:'',registration:'',source:'Apport personnel',status:'À contacter',serviceType:'Remplacement de vitrage',estimatedAmount:0,paidAmount:0,generatedRevenue:0,appointmentAt:null,satisfactionStars:null,nextAction:'Rappeler le client',nextActionAt:null,lastContactAt:null,consentStatus:'À vérifier',notes:''});
 async function save(e:React.FormEvent){e.preventDefault();if(blocked||!editing)return;if(!editing.name.trim()||!editing.registration.trim())return;const existing=!!editing.id;try{const r=await fetch(existing?`/api/individuals/${editing.id}`:'/api/individuals',{method:existing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});if(r.status===401){location.href='/login';return}if(r.status===409){alert('Cette immatriculation existe déjà dans les particuliers actifs.');return}if(!r.ok)throw new Error();const d=await r.json();setItems(old=>existing?old.map(x=>x.id===editing.id?d.item:x):[d.item,...old]);setOpen(false)}catch{setBlocked(true);alert('Enregistrement impossible. La donnée n’a pas été validée par le serveur.')}}
 async function remove(){if(!editing?.id||blocked)return;try{const r=await fetch(`/api/individuals/${editing.id}`,{method:'DELETE'});if(r.status===401){location.href='/login';return}if(!r.ok)throw new Error();setItems(old=>old.filter(x=>x.id!==editing.id));setOpen(false)}catch{setBlocked(true);alert('Archivage impossible.')}}
 const dateField=(label:string,key:'appointmentAt'|'nextActionAt'|'lastContactAt')=><label>{label}<input type="datetime-local" value={toLocal(editing?.[key]||null)} onChange={e=>editing&&setEditing({...editing,[key]:e.target.value?new Date(e.target.value).toISOString():null})}/></label>;
 return <>
  <div className="workspacebar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher nom, téléphone, e-mail, véhicule, immatriculation…"/><button className="primary" onClick={()=>{if(blocked){alert('Stockage sécurisé indisponible.');return}setEditing(fresh());setOpen(true)}}>＋ Ajouter un particulier</button></div>
  <div className="prospectcards">{filtered.map(p=><article className="prospectcard" key={p.id} onClick={()=>{setEditing(p);setOpen(true)}}><div className="prospectscore">{p.registration.slice(0,2)||'—'}</div><div className="prospectmain"><div><h2>{p.name}</h2><p>{p.vehicle||'Véhicule à renseigner'} • {p.registration}</p></div><mark>{p.status}</mark><div className="prospectmeta"><span>☎ {p.phone||'Téléphone à renseigner'}</span><span>€ encaissé {money(p.paidAmount)} / devis {money(p.estimatedAmount)}</span><span>{p.nextAction||p.source}{p.nextActionAt?` · ${new Date(p.nextActionAt).toLocaleDateString('fr-FR')}`:''}</span><span>{p.satisfactionStars?`Satisfaction ${'★'.repeat(p.satisfactionStars)}`:'Satisfaction à recueillir'}</span></div><small>{p.notes}</small></div><button className="edit">Modifier →</button></article>)}</div>
  {!blocked&&filtered.length===0&&<section className="mailPanel">Aucun particulier ne correspond à cette recherche.</section>}
  {open&&editing&&<div className="modalback" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="modalhead"><div><p className="eyebrow">FICHE PARTICULIER</p><h2>{editing.name||'Nouveau particulier'}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="formgrid">
   <label>Nom / Prénom<input required autoFocus value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Immatriculation<input required value={editing.registration} onChange={e=>setEditing({...editing,registration:e.target.value.toUpperCase()})}/></label><label>Téléphone<input inputMode="tel" value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})}/></label><label>E-mail<input type="email" value={editing.email||''} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><label>Véhicule<input value={editing.vehicle} onChange={e=>setEditing({...editing,vehicle:e.target.value})}/></label><label>Prestation<select value={editing.serviceType} onChange={e=>setEditing({...editing,serviceType:e.target.value})}><option>Remplacement de vitrage</option><option>Remplacement de pare-brise</option><option>Autre vitrage</option><option>Réparation</option></select></label><label>Statut<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>À contacter</option><option>RDV</option><option>Réalisé</option><option>Perdu</option></select></label>{dateField('Rendez-vous','appointmentAt')}<label>Montant devis (€)<input type="number" min="0" step="0.01" value={editing.estimatedAmount} onChange={e=>setEditing({...editing,estimatedAmount:Number(e.target.value)})}/></label><label>Montant encaissé (€)<input type="number" min="0" step="0.01" value={editing.paidAmount} onChange={e=>setEditing({...editing,paidAmount:Number(e.target.value)})}/></label><label>CA réalisé (€)<input type="number" min="0" step="0.01" value={editing.generatedRevenue} onChange={e=>setEditing({...editing,generatedRevenue:Number(e.target.value)})}/></label><label>Satisfaction<select value={editing.satisfactionStars||''} onChange={e=>setEditing({...editing,satisfactionStars:e.target.value?Number(e.target.value):null})}><option value="">Non renseignée</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{'★'.repeat(n)} ({n}/5)</option>)}</select></label><label>Accord de contact<select value={editing.consentStatus} onChange={e=>setEditing({...editing,consentStatus:e.target.value})}><option>À vérifier</option><option>Accord donné</option><option>Refusé</option></select></label><label>Prochaine action<input value={editing.nextAction} onChange={e=>setEditing({...editing,nextAction:e.target.value})} placeholder="Ex. Confirmer le rendez-vous"/></label>{dateField('Échéance de suivi','nextActionAt')}{dateField('Dernier contact','lastContactAt')}<label>Source<input value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value})}/></label><label className="full">Notes<textarea rows={3} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label>
  </div><div className="modalactions">{editing.id&&<button type="button" className="danger" onClick={remove}>Archiver</button>}<button type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="primary">Enregistrer</button></div></form></div>}
 </>;
}
