'use client';
import {useEffect,useMemo,useState} from 'react';

type Stage='À contacter'|'Qualifiés'|'RDV'|'Offres'|'Gagnés';
type StoredProspect={id:number;name:string;score:number;next?:string;zone?:string;status?:string;fleet?:string;sector?:string;access?:string;insurance?:string;potentialRevenue?:number;signedRevenue?:number;generatedRevenue?:number;updatedAt?:string;[key:string]:unknown};
type Deal=StoredProspect&{stage:Stage;next:string};
const KEY='rapid-pb-prospects-v1';
const stages:Stage[]=['À contacter','Qualifiés','RDV','Offres','Gagnés'];
const seed:Deal[]=[{id:1,name:'Azur Baie',stage:'RDV',status:'RDV',score:94,next:'Préparer le RDV',zone:'Marseille 10e',fleet:'6–12',potentialRevenue:1800},{id:2,name:'Provence Clim Services',stage:'Qualifiés',status:'Qualifié',score:87,next:'Proposer un RDV',zone:'Marseille 11e',fleet:'4–8',potentialRevenue:900}];
const money=(n=0)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const toStage=(s='Nouveau'):Stage=>s==='Gagné'?'Gagnés':s==='Offre'?'Offres':s==='RDV'?'RDV':s==='Qualifié'||s==='Relance'?'Qualifiés':'À contacter';
const toStatus=(s:Stage)=>s==='Gagnés'?'Gagné':s==='Offres'?'Offre':s==='RDV'?'RDV':s==='Qualifiés'?'Qualifié':'À contacter';
const action=(s:Stage)=>s==='Gagnés'?'Fidéliser le partenaire':s==='Offres'?'Relancer et sécuriser la décision':s==='RDV'?'Préparer le RDV':s==='Qualifiés'?'Proposer un RDV':'Qualifier et contacter';
function isStored(x:unknown):x is StoredProspect{return typeof x==='object'&&x!==null&&'id'in x&&'name'in x&&'score'in x}
function fleetMid(f=''){const n=(f.match(/\d+/g)||[]).map(Number);return n.length>1?(n[0]+n[n.length-1])/2:n[0]||0}
function recalc(p:StoredProspect,status:string){if(status==='Perdu')return 0;const vehicles=fleetMid(p.fleet);if(!vehicles)return p.potentialRevenue||0;const sw:Record<string,number>={'Nouveau':.2,'À contacter':.25,'Relance':.35,'Qualifié':.5,'RDV':.65,'Offre':.8,'Gagné':1};const aw:Record<string,number>={'À vérifier':.8,'Excellent':1.05,'Bon':1,'Moyen':.85,'Difficile':.6};const iw:Record<string,number>={'À vérifier':.85,'Faible':1,'Moyenne':.8,'Forte':.55};const exposure=/BTP|CVC|Maintenance|Paysage|Nettoyage|Livraison|Transport|Ambulance|Taxi/i.test(String(p.sector||''))?1.15:1;return Math.round(vehicles*450*.65*(sw[status]??.2)*(aw[String(p.access||'À vérifier')]??.8)*(iw[String(p.insurance||'À vérifier')]??.85)*exposure/50)*50}
export default function PipelineBoard(){
 const[deals,setDeals]=useState<Deal[]>(seed);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(!raw)return;const parsed:unknown=JSON.parse(raw);if(Array.isArray(parsed)){const valid=parsed.filter(isStored).filter(x=>x.status!=='Perdu');if(valid.length)setDeals(valid.map(x=>({...x,stage:toStage(x.status),next:x.next||action(toStage(x.status))})))}}catch{}},[]);
 const stats=useMemo(()=>{const active=deals.filter(d=>d.stage!=='Gagnés'),potential=active.reduce((a,d)=>a+(d.potentialRevenue||0),0),signed=deals.reduce((a,d)=>a+(d.signedRevenue||0),0),hot=deals.filter(d=>d.stage==='RDV'||d.stage==='Offres').length;return{active,potential,signed,hot}},[deals]);
 function move(d:Deal,dir:number){const i=stages.indexOf(d.stage),n=i+dir;if(n<0||n>=stages.length)return;const stage=stages[n],next=action(stage),status=toStatus(stage),potentialRevenue=recalc(d,status);setDeals(old=>old.map(x=>x.id===d.id?{...x,stage,next,status,potentialRevenue}:x));try{const raw=localStorage.getItem(KEY);if(!raw)return;const parsed:unknown=JSON.parse(raw);if(Array.isArray(parsed)){const all=parsed.filter(isStored);localStorage.setItem(KEY,JSON.stringify(all.map(x=>x.id===d.id?{...x,status,next,potentialRevenue,updatedAt:new Date().toISOString().slice(0,10)}:x)))}}catch{}}
 return <>
  <section className="pipelineHero"><div><p className="eyebrow">PILOTAGE COMMERCIAL</p><h2>Du premier contact au partenaire actif</h2><p>Chaque mouvement met à jour le statut du prospect et son potentiel pondéré dans le CRM.</p></div><div className="pipelineKpis"><div><small>OPPORTUNITÉS ACTIVES</small><b>{stats.active.length}</b></div><div><small>POTENTIEL PONDÉRÉ</small><b>{money(stats.potential)}</b></div><div><small>RDV + OFFRES</small><b>{stats.hot}</b></div><div><small>CA SIGNÉ RENSEIGNÉ</small><b>{money(stats.signed)}</b></div></div></section>
  <div className="pipelineLegend"><span><i/> À travailler</span><span><i/> En progression</span><span><i/> Proche décision</span><span className="pipelineHint">Priorité : faire avancer les dossiers, pas remplir des colonnes.</span></div>
  <div className="kanban">{stages.map((stage,i)=>{const list=deals.filter(d=>d.stage===stage).sort((a,b)=>(b.potentialRevenue||0)-(a.potentialRevenue||0));const total=list.reduce((a,d)=>a+(d.potentialRevenue||0),0);return <section className={`kanbancol stage${i}`} key={stage}><header><div><b>{stage}</b><small>{money(total)}</small></div><span>{list.length}</span></header><div className="kanbanCards">{list.map(d=><article className="dealcard" key={d.id}><div className="dealTop"><small>{d.sector||'PROSPECT B2B'}</small><span className={d.score>=85?'hotScore':'score'}>{d.score}/100</span></div><h3>{d.name}</h3><p className="dealMeta">{d.zone||'Zone à renseigner'}{d.fleet?` · 🚐 ${d.fleet}`:''}</p><div className="dealValue"><small>POTENTIEL CRM</small><b>{money(d.potentialRevenue)}</b></div><div className="nextAction"><small>PROCHAINE ACTION</small><p>{d.next}</p></div><div className="dealSignals"><span>Accès {d.access||'à vérifier'}</span><span>Assurance {d.insurance||'à vérifier'}</span></div><footer><button disabled={i===0} onClick={()=>move(d,-1)} aria-label="Reculer l'opportunité">←</button><button className="advance" disabled={i===stages.length-1} onClick={()=>move(d,1)}>{i===stages.length-1?'Partenaire actif':'Avancer →'}</button></footer></article>)}{!list.length&&<div className="emptyStage"><b>Colonne vide</b><span>{i===0?'Les nouveaux prospects apparaîtront ici.':'Fais avancer les opportunités depuis la colonne précédente.'}</span></div>}</div></section>})}</div>
 </>
}