import { NextRequest, NextResponse } from "next/server";
import { authConfigured, sessionValid } from "../../../lib/auth";
import { databaseConfigured, db } from "../../../lib/db";
import { ensureCrmSchema } from "../../../lib/ensure-schema";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const headers={"Cache-Control":"no-store"}, periods=new Set(["daily","weekly","monthly","yearly"]);
async function guard(){if(!databaseConfigured())return NextResponse.json({error:"database_not_configured"},{status:503,headers});if(!authConfigured()||!(await sessionValid()))return NextResponse.json({error:"unauthorized"},{status:401,headers});await ensureCrmSchema();return null}
export async function GET(){const denied=await guard();if(denied)return denied;try{const tasks=await db()`select id,title,details,period,priority,due_at as "dueAt",recurring,status,created_at as "createdAt" from commercial_routine_tasks where status='open' order by due_at asc nulls last,priority desc,created_at desc limit 200`;return NextResponse.json({tasks},{headers})}catch{return NextResponse.json({error:"routines_unavailable"},{status:503,headers})}}
export async function POST(req:NextRequest){const denied=await guard();if(denied)return denied;let x:any;try{x=await req.json()}catch{return NextResponse.json({error:"invalid_request"},{status:400,headers})}try{if(x.action==="close"){const id=String(x.id||""),status=x.status==="dismissed"?"dismissed":"completed";if(!/^[0-9a-f-]{36}$/i.test(id))return NextResponse.json({error:"invalid_id"},{status:400,headers});const result=await db().begin(async sql=>{const rows=await sql`update commercial_routine_tasks set status=${status},completed_at=case when ${status}='completed' then now() else null end,updated_at=now() where id=${id} and status='open' returning title,details,period,priority,due_at as "dueAt",recurring`;if(rows.length&&rows[0].recurring&&status==='completed'){await sql`insert into commercial_routine_tasks(title,details,period,priority,due_at,recurring) values(${rows[0].title},${rows[0].details},${rows[0].period},${rows[0].priority},greatest(coalesce(${rows[0].dueAt},now()),now())+case ${rows[0].period} when 'daily' then interval '1 day' when 'weekly' then interval '1 week' when 'monthly' then interval '1 month' else interval '1 year' end,true)`}return rows.length>0});return NextResponse.json({ok:result},{headers})}
 const title=String(x.title||"").trim().slice(0,180),period=String(x.period||"daily"),details=String(x.details||"").trim().slice(0,1000),priority=Math.max(0,Math.min(100,Number(x.priority)||60));if(!title||!periods.has(period))return NextResponse.json({error:"invalid_task"},{status:400,headers});const dueAt=x.dueAt?new Date(x.dueAt):null;if(dueAt&&Number.isNaN(dueAt.getTime()))return NextResponse.json({error:"invalid_due_date"},{status:400,headers});const rows=await db()`insert into commercial_routine_tasks(title,details,period,priority,due_at,recurring) values(${title},${details||null},${period},${priority},${dueAt?.toISOString()||null},${Boolean(x.recurring)}) returning id,title,details,period,priority,due_at as "dueAt",recurring,status,created_at as "createdAt"`;return NextResponse.json({task:rows[0]},{status:201,headers})}catch{return NextResponse.json({error:"routine_save_failed"},{status:503,headers})}}
